""""Manually curated data used for data processing & querying."""

#based on Westie DJs https://docs.google.com/spreadsheets/d/1zP8LYR9s33vzCGAv90N1tQfQ4JbNZgorvUNnvh1PeJY
actual_wcs_djs = ['12149954698', '1128646211', 'alicia.writing', '1141617915', 'chrisbloecker', '7r53jcujuc31b9bmur1kdk6j8', '11124055499',
'1154418581', 'lanyc13', 'idcmp2', 'james93uk', 'jacinthe.r', '1214584555', '216rwad76ay2yufv6wdksnbvi', 'lutynka',
'1185428002', 'ichikoo', '1181723092', '1229065119', '11164785980', 'rafalzonk', '11170824661', '1114726702', 'sepgod',
'blitzemp', '1195256212', 'vincentmoi54', 'saf2ousfteo2zwin3ysb71uc4', 'gj39mpctu2splzc3yjov5ph80', 'stoune', '1136143824',
'225x7krl3utkpzg34gw3lhycy', 'timo-2000-de', 'aennabanaenas', '21nse7ljtz2chhqdqi7onh4zi', 'armand1989', '1167150164',
'1121756047', 'tourflo', 'drjessdc', 'califf_wcs', 'kthiran', '1136143824', '11156835879', 'ahammar', 'foo7pbdux9qf50en3fnl1hnqk',
'vgvttofujh6h2qhz1dllwipgw', 'rhoades.elaine', '11149778648', '11168063242', '1262866465', '1227130632',
'31ww73dlraaawzixnk5xic7zn5d4', '1112522347', 'kfal92', 'hasskt', '21n5wwkfegd4ssz2xjaunjcja', '1160072156', 'siverin',
'31crk5spdq5bwf2niasjvmazkcee', '31cadxxcjjyxtogwamke25v5ljaq', '31px4eoamsjrpiptxvptk2mc3yx4', '1112824750', '12134184020',
'21xjgpvredrh5mms5eg4nllya', '31ecz63iftaszwketoy7pjxyhk74', '31qqbghffeq6punchuj7yoqs3vfy?si=25fac0caa6cb4077', 'djkarcheng',
'djmotionwcs', 'silentsoliloquy24', 'thethas', 'tom.esca', 'valdho', '11149862781']

#based on https://www.reddit.com/r/popheads/comments/108klvf/a_comprehensive_list_of_lgbtq_pop_music_acts/
# and https://www.reddit.com/r/popheads/comments/c3rpga/happy_pride_in_honor_of_the_month_here_is_a_list/
# and https://www.reddit.com/r/Monstercat/comments/ueqi9f/lgbtq_edm_artists/
# https://www.reddit.com/r/popheads/comments/h0fbxn/happy_pride_month_heres_a_list_of_some_lgbt/
# and lots of googling + chatGPT

# https://docs.google.com/spreadsheets/d/1-elrLd_3tX4QTLQjj4EmPxRSzXHcxs6tZp5Y5fRFalc/edit?usp=sharing
poc_artists = [name.lower() for name in [
'27Delly', 'ABIR', 'AFROJACK', 'ALTÉGO', 'AWA', 'Aaradhna', 'Aaries', 'Aaron Frazer', 'Aaron Neville', 'Abhi The Nomad',
'Adi Oasis', 'Ady Suleiman', 'Al Green', 'Alex Newell', 'Alexander Oscar', 'Alextbh', 'Alicia Keys', 'Alvin Garrett', 'Amanda Yang',
'Amber Mark', 'Anderson .Paak', 'Angela Johnson', 'Anthony Ramos', 'Appleby', 'Aretha Franklin', 'Arlene Zelina',
'Arthur Adams', 'Ashanti', 'Ashley DuBose', 'Ashley Mehta', 'B.B. King', 'B.o.B', 'BABYMONSTER', 'BAYNK',
'BLACKPINK', 'BTS', 'Beau Diako', 'Ben&Ben', 'Beyoncé', 'Black Eyed Peas', 'Black Pumas',
'Blithe', 'Bluey Robinson', "Blush'ko", 'Blxst', 'Boyz II Men', 'Brandon Beal', 'Brandy', 'Brother Yusef',
'Bruno Mars', 'Bryce Vine', 'Bryson Tiller', 'Burna Boy', 'CHUNG HA', 'CLAY', 'Caleborate', 'Calimossa',
'Camila Cabello', 'Carlos Santana', 'Carneyval', 'Cat Burns', 'Charlie Wilson', 'Chiiild', 'Chris Thomas King',
'Christian Scott aTunde Adjuah', 'Ciara', 'Cleo Sol', 'Col3trane', 'Corinne Bailey Rae', 'Cruel Santino',
'D-Hack', 'D-Nice', 'D.O.E.', 'DJ Khaled', 'DaBaby', 'Dane Amar', 'Darius', 'Darius Coleman', 'Davido', 'Delilah Montagu',
'Dhibu Ninan Thomas', 'Doechii', 'Doja Cat', 'Don Toliver', 'Dru Hill', 'Duckwrth', 'Durand Bernarr',
'Durand Jones & The Indications', 'EZI', 'Ella Mai', 'Emily King', 'Emotional Oranges',
'Empire Cast', 'Enrique Iglesias', 'Eric Benét', 'Eric Bibb', 'Eric Nam', 'Erykah Badu', 'Eryn Allen Kane', 'Etta James', 'Everett Bradley',
'FHAT', 'FKJ', 'Faouzia', 'Fenton Robinson', 'Floyd Fuji', 'Foxy Brown',
'Frank Ocean', 'Funk Wav', 'GIMS', 'Gary Clark Jr.', 'Gen Hoshino', 'Gerald Levert', 'Ginuwine', 'Griff',
'H.E.R.', 'HARLOE', 'HONNE', 'Hailee Steinfeld', 'Hanz', 'Hayley Kiyoko', 'Hil St. Soul', 'Hollie Carmen', 'Hongjoong of ATEEZ',
'IDRIS', 'Ife Kehinde', 'India.Arie', 'Isaac Dunbar', 'Izzy Bizu', 'J. Brown', 'JAIE', 'JAY-Z', 'Ja Rule', 'Janet Jackson',
'Jany Green', 'Jared Brady', 'Jarreau Vandal', 'Jasmine Thompson', 'Jason Derulo', 'Jay Sean', 'Jay Wile', 'Jay-Way', 'Jeezy',
'Jereena Montemayor', 'Jessica Domingo', 'Jhameel', 'John Legend', 'Jon Batiste', 'Jon Mero', 'Jonita Gandhi',
'Jordin Sparks', 'Jorja Smith', 'Josh Tobias', 'Joy Crookes', 'Joy Oladokun', 'Justine Skye', 'KAMAUU',
'KAYTRANADA', 'KWAYE', 'Kaiya', 'Kamakshi Khanna', 'Kane Brown', 'Kapil Kapilan', "Keb' Mo'", 'Kendrick Lamar', 'Kent Jones', 'Keri Hilson',
'Kevin Michael', 'Khalid', 'KiNG MALA', 'Kiana Ledé', 'Kim Petras', 'Kina Grannis', 'King George', 'Kodak Black', 'Koffee Brown',
'Kyshona', "L'Impératrice", 'LIE NING', 'LU KALA', 'LaMorris Williams', 'Latasha Lee', 'Latto',
'Lauren Jauregui', 'Ledisi', 'Leon Bridges', 'Lianne La Havas', 'Lil Halima', 'Lil Jon', 'Little Mix',
'Lizzo', 'Lori Jenaire', 'Lucky Daye', 'Ludacris', 'Luke James', 'Lyn Lapid', 'MICHELLE', 'MILCK', 'MONTMARTRE',
'Mabel', 'Mahalia', 'Maisie Peters', 'Maiya Sykes', 'Majid Jordan', 'Mali Music',
'Mapei', 'Mariah Carey', 'Mario', 'Marwin', 'Masego', 'Maxwell', 'Maze & Frankie Beverly', 'Mega', 'Megan Thee Stallion',
'Meridian', 'Metropole Orkest', 'Midas Hutch', 'Miguel', 'Musiq Soulchild', 'NEZZA', 'NNAVY', 'Nahko And Medicine For The People',
'Navy', 'Nayer', 'Ne-Yo', 'Nelly', 'Nico & Vinz', 'Noah Slee', 'Normani', 'Now United', 'NuChoyce', 'Nylo', 'Olivia Dean',
'Otis Kane', 'Otis Redding', 'P.Keys', 'P3GI-13', 'PJ Morton', 'Parson James', 'Patrik Jean', 'Paulo Londra', 'Pentatonix',
'Pharrell Williams', 'Phon', 'Phony Ppl', 'Pink Sweat$', 'Pitbull', 'Playboi Carti', 'Prince', 'Q',
'Q-Tip', 'Queen D', 'Queen Latifah', 'R.LUM.R', 'Raiche', 'Raleigh Ritchie', 'Ray Dalton', 'Revel Day', 'Rita Ora', 'Ruth B.', 'RuthAnne',
'Ruthie Foster', 'SERA', 'SOLOMON', 'SZA', 'Sadie', 'Saffire-The Uppity Blues Women',
'Saint Joshua', 'Samm Henshaw', 'Sampha', 'Sandro Cavazza', 'Scary Pockets', 'Sean Paul', 'Sebastian Yatra', 'Selena Gomez',
'Seori', 'Sickick', 'Silk Sonic', 'Smokey James & the Avalanche', 'Snoh Aalegra', 'Snoop Dogg', 'Social House', 'Solange',
'Sophia Bromberg', 'Soul For Real', 'Stromae', 'Sunshine Anderson', 'Superfruit', 'Swae Lee', 'T-Pain', 'TAEYEON',
'THE ANXIETY', 'TLC', 'Tai Verdes', 'Takara', 'Tamia', 'Tank', 'Tank and The Bangas', 'Tash Sultana', 'Taste of Pluto',
'Tems', 'Tessa Violet', 'The Acoustic Room', 'The Marías', 'The Notorious B.I.G.', 'The Weeknd', 'Thirdstory',
'Timbaland', 'Tinashe', 'Todrick Hall', 'Tove Lo', 'Trey Songz', 'Trinix', 'Ty Dolla $ign', 'Tyler Cole',
'UNO Stereo', 'USHER', 'Uncle Maximilien', 'Unlike Pluto', 'VanJess', 'Victor Franco', 'Vory', 'Véyah', 'WAYNE SNOW', 'WILLOW',
'WOOSUNG', 'Wafia', 'Will Smith', 'William Singe', 'Wiz Khalifa', 'Wizkid', 'Xavier Omär', 'YAØ', 'YongYong', 'Young Cocoa', 'Young Thug',
'Yuna', 'ZAYN', 'Zacari', 'Zach Ezzy', 'Zaeden', 'eaJ', 'emawk', 'keshi', 'lost spaces', 'morgxn', 'mxmtoon', '张天枢',
'Amber Navran', 'Buddy', 'Chika', 'Duckie', 'Duckie Thot', 'Leikeli47', 'Nao', 'Ravyn Lenae', 'Tierra Whack', 'Tobe Nwigwe',
"Big Mama Thornton", "Son House", "Skip James", "Lightnin' Hopkins", "Junior Kimbrough", "R.L. Burnside", "Mississippi Fred McDowell",
"Big Bill Broonzy", "Memphis Minnie", "Rev. Gary Davis", "Blind Lemon Jefferson", "Blind Willie Johnson", "Blind Willie McTell",
"Taj Mahal", "Corey Harris", "Otis Rush", "Buddy Guy", "Lurrie Bell", "Albert King", "Freddie King", "Little Milton", "Johnny Copeland",
"Luther Allison", "Robert Cray", "Lucky Peterson", "Clarence 'Gatemouth' Brown", "Big Jack Johnson", "Shannon Curfman", "Joanna Connor",
"Toronzo Cannon", "Shemekia Copeland", "Eric Gales", 'Christone "Kingfish" Ingram', "Shemekia Copeland", "Eric Gales",
"Gary Clark Jr.", "Fantastic Negrito", "Joe Louis Walker", "Selwyn Birchwood", "Adia Victoria", "Buffalo Nichols", "Jackie Venson",
"Jontavious Willis", "Sugaray Rayford", "Mr. Sipp", "Vanessa Collier", "Marquise Knox", "Shemekia Copeland", "Eric Gales",
"Toronzo Cannon", "Gary Clark Jr.", "Fantastic Negrito", "Joe Louis Walker", "Selwyn Birchwood", "Adia Victoria", "Buffalo Nichols",
"Jackie Venson", "Jontavious Willis", "Sugaray Rayford", "Mr. Sipp", "Vanessa Collier", "Marquise Knox", 'Temani', 'Ambré', 'Tyla',
'Libianca', 'Thuy', 'Thuy My', 'Arin Ray', 'Cautious Clay', 'Baby Rose', 'Bree Runway', 'Lola Brooke', 'Dope Lemon', 'Ebenezer',
'Fousheé', 'GIVĒON', 'Jozzy', 'Marzz', 'Tone Stith', 'Nao Yoshioka', 'PinkPantheress', 'RINI', 'Sinead Harnett', 'Toian', 'Umi Copper',
'Zyah Belle', 'Rayana Jay', 'Shaé Universe', 'Amaria', 'Mikhala Jené', 'Destiny Rogers', 'Tamera', 'Sinego', 'Lila Iké', 'Elaine',
'Jada Kingdom', 'Ayra Starr', 'Bloody Civilian', 'Omah Lay', 'Fireboy DML', 'CKay', 'Reminisce', 'Joeboy', 'Asake', 'Bella Shmurda',
'Adekunle Gold',
 ]]

queer_artists = [name.lower() for name in [
'070 Shake', '100 gecs', 'ADONXS', 'AKVMA', 'Abdu Ali', 'Adam Lambert', 'Adeem the Artist', 'Adore Delano', 'Adrianne Lenker',
'Against Me!', 'Akeos', 'Akira Complex', 'Alabama Shakes', 'Alex Chapman', 'Alex the Astronaut', 'Alexandra Stan', 'Amaarae',
'Amaryllis', 'Ambré', 'Amorphous', 'Amos Milburn', 'Ana Frango Elétrico', 'Andrew Bayer', 'Andy Bey', 'Angel Haze', 'Angel Olsen',
'Angel Olson', 'Anitta', 'Anne-Marie', 'Anohni', 'Anthony Green', 'Anthony Lexa', 'Arca', 'Ariel Zetina', 'Arlo Parks',
'Army of Lovers', 'Arthur Russell', 'Ashley Frangipane', 'Ashnikko', 'Aurora', 'Azealia Banks', 'BROCKHAMPTON', 'Baby Queen',
'Baby Tate', 'Bambie Thug', 'Barry Manilow', 'Bartees Strange', 'Basement Pony', 'Bauhaus', 'Ben Abraham', 'Ben Platt', 'Ben Webster',
'Benjamin Britten', 'Benson Boone', 'Bentley Robles', 'Bessie Smith', 'Beth Ditto', 'Betty Who', 'Big Freedia', 'Big Joanie',
'Big Joe Turner', 'Big Mama Thornton', 'Big Thief', 'Billie Eilish', 'Billie Holiday', 'Billy Porter', 'Billy Strayhorn', 'Billy Wright',
'Black Belt Eagle Scout', 'Black Dresses', 'Blue Rojo', 'Bonnie Fraser', 'Boy George', 'Boygenius', 'Boyish', 'Brandi Carlile',
'Brayton Bowman', 'Bright Light Bright Lights', 'Bronze Avery', 'Brooke Candy', 'Brooke Eden', 'Bunk Johnson', 'Buzzcocks', 'Cain Culto',
'Cakes Da Killa', 'Caleb de Casper', 'Calum Scott', 'Car Seat Headrest', 'Car seat headrest', 'Cardi B', 'Carole Pope', 'Cat Burns',
'Cazwell', 'Cecil Taylor', 'Chandler Leighton', 'Chappell Roan', 'Charli xcx', 'Chika', 'Christine & The Queens', 'Christine and the Queens',
'Clairo', 'Claud', 'Clementaum', 'Cloudy June', 'Clozee', 'Cobrah', 'Coco & Breezy', 'Coco & Clair Clair', 'Coil', 'Conan Gray',
'Conchita Wurst', 'Convexity', 'Cooza', 'Coudy June', 'Count Basie', 'Courtney Barnett', 'Cub Sport', 'Cuee', 'DJ Aron', 'DJ Sprinkles',
'Dai Burger', 'Dan Haseltine', 'Dani Demand', 'Dapper Dan Midas', 'David Archuleta', 'David Bowie', 'Davy Boi', 'Daya', 'Declan McKenna',
'Demi Lovato', 'Dena DeRose', 'Derrick Carter', 'Desire Marea', 'Destin Conrad', 'Detox', 'Devon Cole', 'Devonté Hynes', 'Diana King',
'Dizzy Fae', 'Dizzy Gillespie', 'Doechii', 'Doja Cat', 'Don Pullen', 'Donnie McClurkin', 'Dorian Electra', 'DossyX', 'Dounia',
'Dove Cameron', 'Dreamer Isioma', 'Drebae', 'Dua Saleh', 'Ducky', 'Duncan Laurence', 'Durand Bernarr', 'Dusty Springfield',
'Eartheater', 'Ejicle', 'Ekko Astral', 'Electrosexual', 'Eli & Fur', 'Elton John', 'Emeline', 'Emily Jeffri', 'Emlyn', 'Empress Of',
'Erasure', 'Eris Drew', 'Ethel Cain', 'Ethel Waters', 'Euphoric Nationacloudyskye', 'Evann Mcintosh', 'Evil', 'Ezra Furman', 'FAYBUL',
'Faith Nolan', 'Farius', 'Felix Jaehn', 'Fever Ray', 'Fletcher', 'Former Hero', 'Frances Forever', 'Frank Ocean', 'Frankie Jaxon',
'Frankie Knuckles', 'Fraxiom', 'Fred Hersch', 'Freddie Mercury', 'G Flip', 'GRiZ', 'Garbage', 'Gary Burton', 'Gaustad', 'Geo Jordan',
'George Michael', 'Gerard Way', 'Girl in Red', 'Girli', 'Gladys Bentley', 'Glass Beach', 'Gorgon City', 'Grace Gaustad', 'Grant Knoche',
'Green Day', 'Greta Van Fleet', 'Greyson Chance', 'HEIDI', 'Halsey', 'Hamed Sinno', 'Hannah Holland', 'Hayley Kiyoko', 'Heems',
'Hercules & Love Affair', 'Hey, Baby', 'Holland', 'Home Is Where', 'Honey Dijon', 'Hop Along', 'Hope Tala', 'Horse McDonald',
'Horse Meat Disco', 'IAMJakeHill', 'IDLES', 'ILoveMakonnen', 'IamJakeHill', 'Iman Jordan', 'India Jordan', 'Iniko', 'Isaac Dunbar',
'Isaiah Rashad', 'Izzy Heltai', 'J. Worra', 'JORDY', 'Jaboukie', 'Jade LeMac', 'Jake Shears', 'Jake Zyrus', 'Jalmaan', 'James Cleveland',
'James Nielsen', 'Jamie Barton', 'Jamila Woods', 'Janelle Monáe', 'Janis Joplin', 'Japanese Breakfast', 'Jason Mraz', 'Jazmin Bean',
'Jennifer Knapp', 'Jeremy Pope', 'Jess Glynne', 'Jessica 6', 'Jiae', 'Jill Sobule', 'Jodie Harsh', 'Joe Talbot', 'John Barrowman', 'John Grant',
'John-Allison Weiss', 'Johnny Mathis', 'Josette Maskin', 'Joy Oladokun', 'Judas Priest', 'Julien Baker', 'July Jones', 'Junglepussy',
'Just B', 'Just Her', 'JustB', 'K Flay', 'KATSEYE', 'KD Lang', 'Kali Uchis', 'Kalifa', 'Kamaiyah', 'Kandy', 'Karin Ann', 'Katie Gavin',
'Katy Perry', 'Kaytranada', 'Keanan', 'Kehlani', 'Keiynan Lonsdale', 'Kele Okereke', 'Kelechi', 'Kelela', 'Keo Nozari', 'Kesha', 'Kevin Abstract',
'Kevin Terry', 'Kidd Kenn', 'Kiddy Smile', 'Kim Ann FoxmaMCMLXXXV', 'Kim Petras', 'King Mala', 'King Princess', 'Kittens', 'Klaus Nomi', 'Kučka',
'Kwaye', 'Kyle Dion', 'L Devine', 'LMA', 'Lady Gaga', 'Lagoona Bloo', 'Lambrini Girls', 'Langston Hughes', 'Larry Gusshee', 'Laura Jane Grace',
'Lauren Jauregui', 'Lava La Rue', 'Le Tigre', 'Leave It On The Floor', 'Left At London', 'Leikeli47', 'Leith Ross', 'Lelowhatsgood', 'Leo Kalyan',
'Leonard Bernstein', 'Lil Aaron', 'Lil Darkie', 'Lil Lotus', 'Lil Nas X', 'Lil Peep', 'Limp Wrist', 'Lionesses', 'Little Richard', 'Lou Reed',
'Lucii', 'Lucy Dacus', 'Lucy Spraggan', 'Luke Evans', 'Lushious Massacr', 'Lynn Gunn (of PVRIS)', 'Lyon Hart', 'Lzzy Hale (of Halestorm)', 'MADGRRL',
'MINOE', 'MNEK', 'MUNA', 'Ma Rainey', 'Mabiland', 'Mad Tsai', 'Madeleine Peyroux', 'Madison Beer', 'Madison Rose', 'Maggie Lindemann', 'Mahawam',
'Mal Blum', 'Mannequin Pussy', 'Marc Almond', 'Maria Becerra', 'Marko Bošnjak', 'Mary Lambert', 'Matt Fishel', 'Maude Latour', 'Mavi Phoenix',
'Max Bemis', 'Maya Jane Coles', 'Meet Me @ The Altar', 'Megan Thee Stallion', 'Mel4Ever', 'Melanie Martinez', 'Meshell Ndegeocello',
'Mia Wray', 'Michael Medrano', 'Michael Tippett', 'Michaela Jai', 'Michelle', 'Mickey Darling', 'Midnight Pool Party', 'Mika', 'Mike Q',
'Mike Servito', 'Mila Jam', 'Miley Cyrus', 'Minute Taker', 'Mista Strange', 'Mitomoro', 'Mitski', 'Mo Heart', 'Molly Grace', 'Monifah',
'Moore Kismet', 'MoreOver', 'Morgxn', 'Moses Sumney', 'Mothica', 'Mrshll', 'Ms.Boogie', 'Mxmtoon', 'Mykki Blanco', 'Måneskin', 'NOFX', 'NSYNC',
'Naeem', 'Nakhane', 'Nakura', 'Naomi McPherson', 'Neko Case', 'NoSo', 'Noah Davis', 'Noahfinnce', 'Nxdia', 'Octo Octa', "Olivia O'Brien",
'Olly Alexander', 'Olly Alexander (Years & Years)', 'Olly Alexander (of Years & Years)', 'Omar Apollo', 'Oncill', 'Or:la', 'Orion Sun',
'Orville Peck', 'Oscar Peterson', 'Oscar and the Wolf', 'O’Hooley & Tidow', 'PVRIS', 'PWR BTTM', 'Pabllo Vittar', 'Paisley Fields',
'Panic! At The Disco', 'Park Hye Jin', 'Passion Pit', 'Peach PRC', 'Peaches', 'Pentatonix', 'Perfume Genius', 'Pet Shop Boys', 'Pete Wentz',
'Peter Thomas', 'Phoebe Bridgers', 'Pinkshift', 'Prince', 'Princess Nokia', 'Purple Crush', 'Qaadir Howard', 'Qrion', 'Queen', 'RANI', 'REM',
'REZZ', 'Raveena', 'Ray Boltz', 'Ray Laurel', 'Raye', 'Rebecca Black', 'Remi Wolf', 'Renee Rapp', 'Reneé Rapp', 'Resistance Revival Chorus', 'Rezz',
'Rhea Raj', 'Ria Mae', 'Ricky Martin', 'Rina Sawayama', 'Rita Ora', 'Rob Gasser', 'Rob Halford', 'Rob.B', 'Robert Alfons', 'Rodney Chrome',
'Rostam', 'Roxen', 'Royal & The Serpent', 'Royal and the Serpent', 'RuPaul', 'Ruby Waters', 'Ryan Beatty', 'SHERELLE', 'SOPHIE', 'STYKS',
'Saara Aalto', 'Sam Feldt', 'Sam Smith', 'Sasami', 'Saucy Santana', 'Saul Williams', 'Scene Queen', 'Scott Matthew', 'Semler', 'Sera Hyndulla',
'Serpentwithfeet', 'Shamir', 'She/Her/Hers', 'Shura', 'Shygirl', 'Sia', 'Siena Liggins', "Sippin' T", 'Sister Rosetta Tharpe', 'Six: The Musical',
'Skin', 'Skybreak', 'Slayyyter', 'Sleater-Kinney', 'Snow Tha Product', 'Sophie', 'Special Interest', 'Spencer Brown', 'St. Vincent',
'Steve Grand', 'Steve Lacy', 'Sufjan Stevens', 'Superfruit', 'SuperfruitMiley Cyrus', 'Syd', 'Sylvester', 'Synymata', 'Syzy', 'TJ Osborne',
'TT The Artist', 'Tash Sultana', 'Tawnted', 'Taylor Bennett', 'Tears for the Dying', 'Teddy Swims', 'Tegan & Sara', 'Tegan and Sara', 'The Aces',
"The B-52's", 'The Blessed Madonna', "The Judy's", 'The Last Artful, Dodgr', 'The Last Dinner Party', 'The Magnetic Fields', 'The Muslims',
'The Smiths', 'The Stooges', 'The Velvet Underground', 'The Who', 'Thorgy Thor', 'Tiger Goods', 'Tinashe', 'Todrick Hall', 'Tokischa', 'Tonex',
'Tove Styrke', 'Towa Bird', 'Tracy Chapman', 'Trixie Mattel', 'Troye Sivan', 'Tsatsamis', 'Tygapaw', 'Tyler Carter', 'Tyler Glenn',
'Tyler, The Creator', 'VINCINT', 'VOLANT', 'Vain', 'Varien', 'Varuen', 'Vaultboy', 'Vicky Beeching', 'Vicky Vox', 'Victoria Monet', 'Victoria Monét',
'Village People', 'Villano Antillano', 'Volant', 'Voltra', 'WILLOW', 'Wafia', 'Water Spirit', 'Wax Wings', 'Wham!', 'Whitney Houston', 'Will Young',
'Willam', 'William Matthews', 'Wonho', 'Woodkid', 'Worthy', 'Wrabel', 'Wreckno', 'Xana', 'Xiu Xiu', 'YULTRON', 'Yeule', 'Yungblud', 'Yves Tumor',
'Zebra Katz', 'Zolita', 'adam daylight', 'aishii', 'bears in trees', 'blackwinterwells', 'brakence', 'd0llywood1', 'dltzk', 'dsg', 'food house',
'girl in red', 'glaive', 'grape milk', 'gupi', 'gyrofield', 'jasmine.4.t', 'k. d. lang', 'kiraku', 'montykeates', 'quinn', 'sakuraburst',
'scrdycat', 'serpentwithfeet', 'umru', 'underscores', 'voxkai', 'webcage', 'xaviersobased', 'Gossip',
'Adult Mom', 'Foxy Dads', 'Now, Now', 'Pronoun', 'Sad13', 'Sir Babygirl', 'Vanessa Carlton',
'ieuan', 'felix vespestad', 'FHAT', 'TWINKIDS', 'Emily Burns', 'Carlos Vara', 'Leland', 'REYNA', 'Sam Bluer'
]]
